set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME MinGW)
set(
    VCPKG_CHAINLOAD_TOOLCHAIN_FILE
    "${CMAKE_CURRENT_LIST_DIR}/../cmake/toolchains/msys2-clang.cmake"
)
set(VCPKG_ENV_PASSTHROUGH PATH CLASH_NATIVE_MSYS2_BIN CLASH_NATIVE_TARGET_ARCHITECTURE)
